apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-block
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: southIndia
  storageAccount: kubernetesstorageclass
