version: '3'
services:
  frontend:
    image: acramod.azurecr.io/tepbackend:ES
    ports:
      - "80:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_password
