apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicontainer-sdp
spec:
  selector:
    matchLabels:
      app: sdp-multicontainer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sdp-multicontainer
    spec:
      securityContext:
        fsGroup: 10001
      volumes:
        - name: mssql-sdp
          persistentVolumeClaim:
            claimName: multicontainer-sdp-pvc
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: sdp-ui
        image: modstudiocrpoc.azurecr.io/sdp-multicontainer-ui:v1
        ports:
        - containerPort: 8080
      - name: sdp-api
        image: modstudiocrpoc.azurecr.io/sdp-multicontainer-api:v1
        ports:
        - containerPort: 80
      - name: mssql-sdp # container name within the pod.
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
          name: tcpsql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_ENABLE_HADR
          value: "1"
        - name: MSSQL_AGENT_ENABLED
          value: "1"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
             name: mssql-sdp
             key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssql-sdp
          mountPath: "/var/opt/mssql"    