apiVersion: v1
kind: Service
metadata:
  name: multicontainer-sdp-service
spec:
  type: NodePort
  selector:
    app: sdp-multicontainer
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 1433
      targetPort: 1433