apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicontainer-1
spec:
  selector:
    matchLabels:
      app: tep
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: tep
    spec:
      securityContext:
        fsGroup: 10001
      volumes:
        - name: mssql-tep
          persistentVolumeClaim:
            claimName: multicontainer-tep-pvc
#        - name: mssql-tep
#          emptyDir: {}
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: forntend-tep
        image: modstudiocrpoc.azurecr.io/frontend-tep:v20
        ports:
        - containerPort: 8089
      - name: backend-tep
        image: modstudiocrpoc.azurecr.io/tepbackend:v11
        ports:
        - containerPort: 8081
      - name: mssql-tep # container name within the pod.
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
          name: tcpsql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_ENABLE_HADR
          value: "1"
        - name: MSSQL_AGENT_ENABLED
          value: "1"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
             name: mssql
             key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssql-tep
          mountPath: "/var/opt/mssql"    