apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv1
  labels:
    type: local
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"