apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: "azurefile"