apiVersion: v1
kind: Service
metadata:
  name: tep-headless-service
spec:
  selector:
    app: tep-sql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
  clusterIP: None