version: '3.4'

services:
  sqlserverdb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: studio-sdp-db
    environment:
        SA_PASSWORD: "2Secure*Password2"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  studio-sdp-api:
    image: studio-sdp-api:v1
    container_name: studio-sdp-api
    build:
        context: .
        dockerfile: studio-sdp-api/AMDNService/Dockerfile
    ports:
      - "5050:80"    
    depends_on:
          - sqlserverdb  
  studiosdpui:
    image: studio-sdp-ui:v1
    container_name: studio-sdp-ui
    build:
      context: .
      dockerfile: studio-sdp-ui/Dockerfile
    ports:
    - "7070:80"
    depends_on:
          - studio-sdp-api
          - sqlserverdb

  