apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: studio-dev
  name: studiocore-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pod","deployment","services","secrets","pvc"]
  verbs: ["get", "watch", "list", "create", "update", "patch"]