apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kub-studio-core-mssql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: studio-core-mssql-db-container
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "Dxc$2017itp"  # Set your desired SA (System Administrator) password
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"  # Set to "Developer" for the Developer edition
