apiVersion: v1
kind: Service
metadata:
  name: kub-studio-core-mssql-db-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: NodePort
