apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-studio-core-backend-deploy
spec:
  selector:
    matchLabels:
      app: studio-core-backend
      tier: backend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: studio-core-backend
        tier: backend
    spec:
    #  imagePullSecrets:
    #   - name: dsdiwakar-registry-secret
     containers:
      - name: studio-core-backend
        image: studiocore:v2
        ports:
        - containerPort: 8090

