apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-studio-core-ui-deploy
spec:
  selector:
    matchLabels:
      app: studio-ui
      tier: frontend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: studio-ui
        tier: frontend
    spec:
#      imagePullSecrets:
#      - name: my-registry-key
      containers:
      - name: studio-ui
        image: studio-core-ui:v2
        ports:
        - containerPort: 8081




