apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-explorer-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: explorer
          image: 524109048295.dkr.ecr.us-west-2.amazonaws.com/explorer/explorer:nightly
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: explorer-data
              mountPath: /opt/murcs/standalone/data
            - name: explorer-logs
              mountPath: /var/log/murcs
            - name: neo4j-import
              mountPath: /neo4j
          env:
            - name: DS_MURCS_DRIVER
              value: mysql
            - name: DS_MURCS_URL
              value: jdbc:mysql://10.99.152.7:3306/murcs?useLegacyDatetimeCode=false&serverTimezone=UTC
            - name: DS_MURCS_USER
              value: murcs
            - name: DS_MURCS_PASSWORD
              value: murcs
            - name: DS_KEYCLOAK_DRIVER
              value: mysql
            - name: KEYCLOAK_HOST
              value: 10.96.154.177
            - name: KEYCLOAK_PORT
              value: "8080"
            - name: DS_KEYCLOAK_URL
              value: jdbc:mysql://10.99.152.7:3306/keycloak
            - name: DS_KEYCLOAK_USER
              value: keycloak
            - name: DS_KEYCLOAK_PASSWORD
              value: keycloak
            - name: MURCS_HTTP_PORT
              value: "8081"
            - name: LOGLEVEL
              value: INFO
            - name: EXPLORER_HIBERNATE_SEARCH
              value: "true"

      volumes:
        - name: explorer-data
          emptyDir: {}
        - name: explorer-logs
          emptyDir: {}
        - name: neo4j-import
          emptyDir: {}
