apiVersion: v1
kind: Service
metadata:
  name: explorer-db-service
spec:
  selector:
    app: explorer-db
  ports:
  - nodePort: 30255
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort
