apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-explorer-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
        - name: explorer
          image: modstudiocrpoc.azurecr.io/explorer-ui:v1
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: explorer-data
              mountPath: /opt/murcs/standalone/data
            - name: explorer-logs
              mountPath: /var/log/murcs
            - name: neo4j-import
              mountPath: /neo4j
          env:
            - name: DS_MURCS_DRIVER
              value: mysql
            - name: DS_MURCS_URL
              value: jdbc:mysql://20.219.115.58:30255/murcs?useLegacyDatetimeCode=false&serverTimezone=UTC
            - name: DS_MURCS_USER
              value: murcs
            - name: DS_MURCS_PASSWORD
              value: murcs
            - name: DS_KEYCLOAK_DRIVER
              value: mysql
            - name: KEYCLOAK_HOST
              value: 20.219.115.58
            - name: KEYCLOAK_PORT
              value: "31323"
            - name: DS_KEYCLOAK_URL
              value: jdbc:mysql://20.219.115.58:30255/keycloak
            - name: DS_KEYCLOAK_USER
              value: keycloak
            - name: DS_KEYCLOAK_PASSWORD
              value: keycloak
            - name: MURCS_HTTP_PORT
              value: "8081"
            - name: LOGLEVEL
              value: INFO
            - name: EXPLORER_HIBERNATE_SEARCH
              value: "true"

      volumes:
        - name: explorer-data
          persistentVolumeClaim:
            claimName: explorer-data-pvc
        - name: explorer-logs
          persistentVolumeClaim:
            claimName: explorer-logs-pvc
        - name: neo4j-import
          persistentVolumeClaim:
            claimName: neo4j-import-pvc
