apiVersion: v1
kind: Service
metadata:
  name: kub-explorer-app-service
spec:
  selector:
    app: explorer
  ports:
    - name: explorer-port
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
