apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-logs-pvc
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Gi
