apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdp-ui
spec:
  selector:
    matchLabels:
      app: sdp-ui
      tier: frontend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sdp-ui
        tier: frontend
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: sdp-ui
        image: modstudiocrpoc.azurecr.io/local-sdp-ui:v4
        ports:
        - containerPort: 80
        imagePullPolicy: Always
